// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmtnsxvabmnqwotpdxhv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtdG5zeHZhYm1ucXdvdHBkeGh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNzI5NzIsImV4cCI6MjA2MDc0ODk3Mn0.B8tbpFkJIGDPlTUlue25207MnSTA7JxAcMfskU5x0LQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);